Ryan somya extending signup 49
Code-4-Community/lucys-love-bus-backend pull request #112
Opened 2021-03-01 00:55 UTC by rymaju

## Why

Required for https://github.com/Code-4-Community/lucys-love-bus-frontend/pull/63

## This PR

- Added profile_picture to contact and children, able to use S3 to upload images
- Fixed Contact DTO to ensure fields are stored properly

2021-03-02 21:11 UTC, jackblanc requested changes
Looks good, nice work getting image upload working. I left some comments in the SQL files that need to be addressed.

2021-03-02 21:11 UTC, jackblanc commented on api/src/main/java/com/codeforcommunity/dto/protected_user/components/Contact.java
> +      String medications,
🔧 This is something which will affect the API interface. Is there a corresponding frontend change for this? Otherwise, won't this break the old site?

2021-03-02 21:11 UTC, jackblanc commented on api/src/main/java/com/codeforcommunity/dto/protected_user/components/Child.java
> +  public void setProfilePicture(String profilePictureBLOB) {
I don't particularly like `profilePictureBLOB` as a parameter name. The inconsistent casing isn't great. Would prefer to just keep this as `profilePicture`. I think there might also be issues with unmarshaling the request if this doesn't match the field name, but can't be certain on that - usually just keep them the same for consistency.

2021-03-02 21:11 UTC, jackblanc commented on api/src/main/java/com/codeforcommunity/dto/protected_user/components/Contact.java
> +  public void setProfilePicture(String profilePictureBLOB) {
same comment as other DTO

2021-03-02 21:11 UTC, jackblanc commented on persist/src/main/resources/db/migration/V14__AddContactProfilePicture.sql
> +ALTER TABLE contacts ADD COLUMN profilePicture VARCHAR(500) DEFAULT null;
formatting - each part of the statement should be on a new line 
```suggestion
ALTER TABLE contacts 
ADD COLUMN profilePicture VARCHAR(500) DEFAULT NULL;
```
also capitalize NULL in SQL

2021-03-02 21:11 UTC, jackblanc commented on persist/src/main/resources/db/migration/V15__AddChildProfilePicture.sql
> +RENAME COLUMN profilepicture TO profile_picture;
```suggestion
ALTER TABLE children 
ADD COLUMN profile_picture VARCHAR(500) DEFAULT null;

ALTER TABLE contacts
RENAME COLUMN profilePicture TO profile_picture;

```

Few things: 
1. formatting, put things on their own lines.
2. space between separate statements. 
3. profilepicture != profilePicture
4. because this isn't deployed to prod, instead of doing the rename column you could just fix the first migration and/or combine these, you'd just have to clear your local DB. 
5. newline at end of file

2021-03-02 21:11 UTC, jackblanc commented on service/src/main/java/com/codeforcommunity/dataaccess/UserInformationDatabaseOperations.java
> +    System.out.println("At image URL: " + publicImageUrl);
🔪 Either cut this or change to a `logger.info`

2021-03-02 21:11 UTC, jackblanc commented on service/src/test/java/com/codeforcommunity/processor/AnnouncementsProcessorImplTest.java
> +  public void testDeleteAnnouncement() {
What does test delete announcement have to do with this? 🤔

2021-03-04 00:24 UTC, rymaju commented on service/src/main/java/com/codeforcommunity/dataaccess/UserInformationDatabaseOperations.java
> +    System.out.println("At image URL: " + publicImageUrl);
F, ill just delete that

2021-03-04 00:25 UTC, rymaju commented on api/src/main/java/com/codeforcommunity/dto/protected_user/components/Contact.java
> +      String medications,
rip yeah I'll make the changes on the frontend

2021-03-04 00:26 UTC, rymaju commented on service/src/test/java/com/codeforcommunity/processor/AnnouncementsProcessorImplTest.java
> +  public void testDeleteAnnouncement() {
I have no idea, I think it was still hanging around my git history from another PR but hey its another test right?

2021-03-07 16:55 UTC, rymaju commented on api/src/main/java/com/codeforcommunity/dto/protected_user/components/Contact.java
> +      String medications,
https://github.com/Code-4-Community/lucys-love-bus-backend/blob/3de2534ca5643e7fb3fdf81109e5199a5825937e/api/src/main/java/com/codeforcommunity/dto/protected_user/components/Contact.java#L25

This is actually how its supposed to be

2021-03-07 17:05 UTC, rymaju commented
THIS WILL BREAK VUE LLB PRODUCTION

...but we want this because `medication` vs `medications` should not be a thing. I'll link a PR for vue llb that makes the appropriate changes

2021-03-07 18:59 UTC, jackblanc reviewed
Looks good but `profilePictureBLOB` still needs to be updated

2021-03-21 23:09 UTC, rymaju commented
See https://github.com/Code-4-Community/lucys-love-bus-frontend/pull/63

![image](https://user-images.githubusercontent.com/23691775/111923829-74c8f380-8a77-11eb-962f-bedd78e2e535.png)

2021-03-22 21:05 UTC, jackblanc approved these changes
🥳

2021-03-22 22:13 UTC, merged