Add event docs
Code-4-Community/lucys-love-bus-backend pull request #97
Opened 2020-10-07 22:40 UTC by onb6

2020-10-07 23:52 UTC, rymaju requested changes
Looks good, but you accidentally deleted `aws.properties.example`, which we need to keep in the repo! Once you put that back when we should be set to merge this in.

2020-10-07 23:52 UTC, rymaju commented on api/src/main/java/com/codeforcommunity/dto/userEvents/components/RSVP.java
>      return isChild;
Wow, I did not know this was like this. I wonder why they coded it this way?

2020-10-07 23:52 UTC, rymaju commented on common/src/main/resources/properties/aws.properties.example
> -aws_access_key = placeholder_aws_access_key
You accidentally deleted this file! We need this for setup

2020-10-13 19:12 UTC, onb6 commented on api/src/main/java/com/codeforcommunity/dto/userEvents/components/RSVP.java
>      return isChild;
Yeah, I also found this to be very odd. I don't really see any reason why it would be like this, but also I guess it probably isn't creating any issues.

2020-10-13 19:23 UTC, rymaju approved these changes
LGTM!! Great work!

2020-10-13 19:23 UTC, rymaju commented on common/src/main/resources/properties/aws.properties.example
> +aws_access_key = placeholder_aws_access_key
🎉

2020-10-13 19:43 UTC, merged