added public event route
Code-4-Community/lucys-love-bus-backend pull request #98
Opened 2020-10-13 03:15 UTC by varunthakkar1

Description

We need to start exposing certain data publicly for the V2 application, in a non-breaking manner for current production app. Create a new Events router that's not protected, so anyone can hit the routes without an Access Token.

Acceptance Criteria

- New Events Subrouter for public data

- GET route that gets all events in the future

These changes add a new subrouter and processor that handles public requests for events, which is just getEvents for now. Also added a new constructor for SingleEventResponse which eliminates user sensitive fields.

2020-10-13 19:41 UTC, rymaju reviewed
Had a meeting to review, just needs to do some quick routing fixes (keeping the old protected logic). I will need to supplement this with postman testing later (thats my job though!). Overall looks solid.

2020-10-27 00:24 UTC, jackblanc reviewed
Looks great overall! I have some comments please reach out if you have any questions

2020-10-27 00:24 UTC, jackblanc commented on api/src/main/java/com/codeforcommunity/dto/userEvents/responses/SingleEventResponse.java
> +
This may be something that's worth defining separately, potentially as a `PublicSingleEventResponse`. There's a large logical difference between each constructor, with the difference being one of the responses simply cannot be generated without knowing who the user is, so that may warrant a better separation of concerns.

2020-10-27 00:24 UTC, jackblanc commented on api/src/main/java/com/codeforcommunity/rest/ApiRouter.java
> +    router.mountSubRouter("/events_v2", publicEventsRouter.initializeRouter(vertx));
```suggestion
    router.mountSubRouter("/events", publicEventsRouter.initializeRouter(vertx));
```
I think `api/v1/protected/events` and `api/v1/events` is enough of a distinction, and this new route isn't necessarily a full V2, it's just different concerns for what data it returns. also `api/v1/events_v2` looks a bit odd.

2020-10-27 00:24 UTC, jackblanc commented on api/src/main/java/com/codeforcommunity/rest/subrouter/EventsRouter.java
> +import static com.codeforcommunity.rest.RestFunctions.*;
Shoutout to IntelliJ for always doing this

2020-10-27 00:24 UTC, jackblanc commented on api/src/main/java/com/codeforcommunity/rest/subrouter/EventsRouter.java
> +import static com.codeforcommunity.rest.RestFunctions.*;
Please change settings and change this back :)

2020-10-27 00:24 UTC, jackblanc commented on api/src/main/java/com/codeforcommunity/rest/subrouter/PublicEventsRouter.java
> +    List<Integer> intIds = getMultipleQueryParams(ctx, "ids", str -> Integer.parseInt(str));
```suggestion
    List<Integer> eventIds = getMultipleQueryParams(ctx, "ids", str -> Integer.parseInt(str));
```
❓ Is it logically correct to call this eventIds? Is this query param selecting which events are returned? Is it a required parameter?

2020-10-27 00:24 UTC, jackblanc commented on service/src/main/java/com/codeforcommunity/ServiceMain.java
> +import com.codeforcommunity.api.*;
grrrrrrr (I know it's not your fault, I'm angry at IntelliJ for making this a default setting)

2020-10-27 00:24 UTC, jackblanc commented on service/src/main/java/com/codeforcommunity/processor/PublicEventsProcessorImpl.java
> +    List<Events> e = db.selectFrom(EVENTS).where(EVENTS.ID.in(eventIds)).fetchInto(Events.class);
```suggestion
    List<Events> events = db.selectFrom(EVENTS).where(EVENTS.ID.in(eventIds)).fetchInto(Events.class);
```
Even if it's clear to you, it won't always be clear to the next developer

2020-10-27 00:24 UTC, jackblanc commented on service/src/main/java/com/codeforcommunity/processor/PublicEventsProcessorImpl.java
> +    return events.stream()
👍

2020-10-27 00:24 UTC, jackblanc commented on service/src/test/java/com/codeforcommunity/processor/EventsProcessorImplTest.java
> +import static org.jooq.generated.Tables.*;
:)

2020-10-27 00:24 UTC, jackblanc commented on service/src/test/java/com/codeforcommunity/processor/PublicEventsProcessorImplTest.java
> +    myJooqMock.addReturn("SELECT", event1);
@connernilsen Can you explain to me what `"SELECT"` means in the JooqMock?

2020-10-27 00:24 UTC, jackblanc commented on service/src/test/java/com/codeforcommunity/processor/PublicEventsProcessorImplTest.java
> +package com.codeforcommunity.processor;
Assuming that the route optionally takes the eventIds, we should have a test for returning all events regardless of ID

2020-12-21 01:14 UTC, rymaju commented
@varunthakkar1 Any updates on this PR?

2021-01-12 19:45 UTC, liammoyn commented on service/src/test/java/com/codeforcommunity/processor/PublicEventsProcessorImplTest.java
> +    myJooqMock.addReturn("SELECT", event1);
This says when a db call is made that includes SELECT, that call will return `event1`

2021-01-15 18:04 UTC, jackblanc approved these changes

2021-01-15 18:04 UTC, jackblanc commented on service/src/test/java/com/codeforcommunity/processor/EventsProcessorImplTest.java
> +    EventsRecord eventRecord = myJooqMock.getContext().newRecord(EVENTS);
Are these changes intentional?

2021-01-15 18:08 UTC, jackblanc requested changes
Blocking on logic changes here https://github.com/Code-4-Community/c4c-dev-docs/pull/31#pullrequestreview-569487218
Need to return all upcoming events when IDs aren't specified. Otherwise looks great!

2021-01-19 22:54 UTC, jackblanc approved these changes

2021-01-20 01:26 UTC, rymaju approved these changes
LGTM 🎉

2021-01-20 01:26 UTC, rymaju commented on service/src/test/java/com/codeforcommunity/processor/EventsProcessorImplTest.java
> +    EventsRecord eventRecord = myJooqMock.getContext().newRecord(EVENTS);
Lets make sure to run the tests to check that this works fine.

2021-01-20 04:37 UTC, merged